### ISSUE TITLE
Broken due to API update

### ISSUE THREAD

**Issue by tma02** [tma02/spotispy-wallpaper#2]
Spotify now requires a valid user agent when retrieving the OAuth token for the web helper.

**Comment by itsminwoo** [comment]
Sorry, I’m not so good with all these terms.

Is that mean it’s impossible to do it now? Or do I have to do something for it?

The original Spotispy can extract data from spotify, how come this one can’t?

**Comment by tma02** [comment]
No there's already a fix implemented for Spotispy, this is kind of a reminder for me to implement it here as well.

**Comment by itsminwoo** [comment]
Thank you, I hope to see the update soon! I appreciate your quick responses.

**Comment by itsminwoo** [comment]
Thank you very much, I appreciate it.
